module.exports = {
  COMMENT_DATE_FROMNOW: "%v ago",
  COMMENT_DATE_AFTERPARENT: "%v after",
  COMMENT_DATE_FULL: "MM/DD/YY HH:mm",
  COMMENT_DATE_WITHOUTYEAR: "MM/DD HH:mm",

  SORT_FILTER_BUTTON_LABEL: "Sort/Filter",
  SORT_FUNCTION_BARCHART_X_LABEL: "Relevance",
  SORT_FUNCTION_ASC_LABEL: "in ascending order",
  SORT_FUNCTION_DESC_LABEL: "in descending order",
  SORT_FUNCTION_UPVOTE_LABEL: "vote",
  SORT_FUNCTION_UPVOTE_MEASUREMENT_LABEL: "Number of votes",
  SORT_FUNCTION_DATE_LABEL: "date",
  SORT_FUNCTION_DATE_MEASUREMENT_LABEL: "Publication date",
  SORT_FUNCTION_NBCHILDS_LABEL: "answers",
  SORT_FUNCTION_NBCHILDS_MEASUREMENT_LABEL: "Number of direct responses",
  SORT_FUNCTION_NBCHILDSTOTAL_LABEL: "answers (total)",
  SORT_FUNCTION_NBCHILDSTOTAL_MEASUREMENT_LABEL: "Number of total responses"
}
