module.exports = {
  COMMENT_DATE_FROMNOW: '%v ago',
  COMMENT_DATE_AFTERPARENT: '%v after',
  COMMENT_DATE_FULL: 'MM/DD/YY HH:mm',
  COMMENT_DATE_WITHOUTYEAR: 'MM/DD HH:mm',

  SORT_FILTER_BUTTON_LABEL: 'Sort/Filter',
  SORT_FUNCTION_UPVOTE_LABEL : 'vote',
  SORT_FUNCTION_DATE_LABEL : 'date',
  SORT_FUNCTION_NBCHILDS_LABEL : 'answers',
  SORT_FUNCTION_NBCHILDSTOTAL_LABEL : 'answers (total)',
}
