module.exports = {
  COMMENT_DATE_FROMNOW: 'il y a %v',
  COMMENT_DATE_AFTERPARENT: '%v après',
  COMMENT_DATE_FULL: 'DD/MM/YY HH:mm',
  COMMENT_DATE_WITHOUTYEAR: 'DD/MM HH:mm',

  SORT_FILTER_BUTTON_LABEL: 'Trier/Filtrer',
  SORT_FUNCTION_UPVOTE_LABEL : 'vote',
  SORT_FUNCTION_DATE_LABEL : 'date',
  SORT_FUNCTION_NBCHILDS_LABEL : 'réponses',
  SORT_FUNCTION_NBCHILDSTOTAL_LABEL : 'réponses (total)'
}
