module.exports = {
  COMMENT_DATE_FROMNOW: "il y a %v",
  COMMENT_DATE_AFTERPARENT: "%v après",
  COMMENT_DATE_FULL: "DD/MM/YY HH:mm",
  COMMENT_DATE_WITHOUTYEAR: "DD/MM HH:mm",

  SORT_FILTER_BUTTON_LABEL: "Trier/Filtrer",
  SORT_FUNCTION_BARCHART_X_LABEL: "Pertinence",
  SORT_FUNCTION_BARCHART_LEGEND_THIS: "Filtré par cette fonction",
  SORT_FUNCTION_BARCHART_LEGEND_OTHER: "Filtré par une autre fonction",
  SORT_FUNCTION_BARCHART_FILTER_MAX: "MAX",
  SORT_FUNCTION_BARCHART_FILTER_MIN: "MIN",
  SORT_FUNCTION_ASC_LABEL: "dans l'ordre croissant",
  SORT_FUNCTION_DESC_LABEL: "dans l'ordre décroissant",
  SORT_FUNCTION_UPVOTE_LABEL: "vote",
  SORT_FUNCTION_UPVOTE_MEASUREMENT_LABEL: "Nombre de votes",
  SORT_FUNCTION_DATE_LABEL: "date",
  SORT_FUNCTION_DATE_MEASUREMENT_LABEL: "Date de publication",
  SORT_FUNCTION_NBCHILDS_LABEL: "réponses",
  SORT_FUNCTION_NBCHILDS_MEASUREMENT_LABEL: "Nombre de réponses directes",
  SORT_FUNCTION_NBCHILDSTOTAL_LABEL: "réponses (total)",
  SORT_FUNCTION_NBCHILDSTOTAL_MEASUREMENT_LABEL: "Nombre de réponses totales"

}
