module.exports = {
  COMMENT_MARGIN_VERTICAL: 10,
  COMMENT_MARGIN_HORIZONTAL: 30,
  COMMENT_DEFAULT_WIDTH: 300,
  COMMENT_EXPANDED_WIDTH: 450,
  COMMENT_DEFAULT_MAX_HEIGHT: 130,
  COMMENT_EXPANDED_MAX_HEIGHT: 260,

  ANIMATION_TIME: 300,
  SCROLL_ANIMATION_SPEED: 0.3, // < 1

  GOOD_COLOR: '#06B000',
  MIDDLE_COLOR: '#FCD303',
  BAD_COLOR: '#ED0000'
}
